# Konfigurasi Build
# Bagian ini memberi tahu Netlify cara membangun situs Anda.
[build]
  # Perintah yang akan dijalankan untuk membangun proyek.
  # "npm run build" akan menjalankan skrip build dari package.json Anda.
  command = "npm run build"

  # Direktori tempat file-file hasil build disimpan.
  # Vite secara default menempatkan hasilnya di direktori "dist".
  publish = "dist"

# Aturan Pengalihan (Redirects)
# Ini sangat penting untuk aplikasi satu halaman (Single-Page Application) seperti React.
[[redirects]]
  # Mengalihkan semua permintaan...
  from = "/*"
  # ...ke file index.html.
  to = "/index.html"
  # Dengan status HTTP 200 (OK), sehingga browser tahu ini bukan halaman error
  # dan router React dapat mengambil alih navigasi.
  status = 200